//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.24 at 10:24:43 PM CET 
//


package org.hl7.fhir.r4.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for ActionRelationshipType-list.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="ActionRelationshipType-list"&amp;gt;
 *   &amp;lt;restriction base="{http://hl7.org/fhir}code-primitive"&amp;gt;
 *     &amp;lt;enumeration value="before-start"/&amp;gt;
 *     &amp;lt;enumeration value="before"/&amp;gt;
 *     &amp;lt;enumeration value="before-end"/&amp;gt;
 *     &amp;lt;enumeration value="concurrent-with-start"/&amp;gt;
 *     &amp;lt;enumeration value="concurrent"/&amp;gt;
 *     &amp;lt;enumeration value="concurrent-with-end"/&amp;gt;
 *     &amp;lt;enumeration value="after-start"/&amp;gt;
 *     &amp;lt;enumeration value="after"/&amp;gt;
 *     &amp;lt;enumeration value="after-end"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "ActionRelationshipType-list")
@XmlEnum
public enum ActionRelationshipTypeList {


    /**
     * Before Start
     * 
     */
    @XmlEnumValue("before-start")
    BEFORE_START("before-start"),

    /**
     * Before
     * 
     */
    @XmlEnumValue("before")
    BEFORE("before"),

    /**
     * Before End
     * 
     */
    @XmlEnumValue("before-end")
    BEFORE_END("before-end"),

    /**
     * Concurrent With Start
     * 
     */
    @XmlEnumValue("concurrent-with-start")
    CONCURRENT_WITH_START("concurrent-with-start"),

    /**
     * Concurrent
     * 
     */
    @XmlEnumValue("concurrent")
    CONCURRENT("concurrent"),

    /**
     * Concurrent With End
     * 
     */
    @XmlEnumValue("concurrent-with-end")
    CONCURRENT_WITH_END("concurrent-with-end"),

    /**
     * After Start
     * 
     */
    @XmlEnumValue("after-start")
    AFTER_START("after-start"),

    /**
     * After
     * 
     */
    @XmlEnumValue("after")
    AFTER("after"),

    /**
     * After End
     * 
     */
    @XmlEnumValue("after-end")
    AFTER_END("after-end");
    private final java.lang.String value;

    ActionRelationshipTypeList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static ActionRelationshipTypeList fromValue(java.lang.String v) {
        for (ActionRelationshipTypeList c: ActionRelationshipTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
