//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.24 at 10:24:43 PM CET 
//


package org.hl7.fhir.r4.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Actual or  potential/avoided event causing unintended physical injury resulting from or contributed to by medical care, a research study or other healthcare setting factors that requires additional monitoring, treatment, or hospitalization, or that results in death.
 * 
 * &lt;p&gt;Java class for AdverseEvent.Causality complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="AdverseEvent.Causality"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{http://hl7.org/fhir}BackboneElement"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="assessment" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="productRelatedness" type="{http://hl7.org/fhir}string" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="author" type="{http://hl7.org/fhir}Reference" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="method" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdverseEvent.Causality", propOrder = {
    "assessment",
    "productRelatedness",
    "author",
    "method"
})
public class AdverseEventCausality
    extends BackboneElement
{

    protected CodeableConcept assessment;
    protected String productRelatedness;
    protected Reference author;
    protected CodeableConcept method;

    /**
     * Gets the value of the assessment property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getAssessment() {
        return assessment;
    }

    /**
     * Sets the value of the assessment property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setAssessment(CodeableConcept value) {
        this.assessment = value;
    }

    /**
     * Gets the value of the productRelatedness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductRelatedness() {
        return productRelatedness;
    }

    /**
     * Sets the value of the productRelatedness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductRelatedness(String value) {
        this.productRelatedness = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setAuthor(Reference value) {
        this.author = value;
    }

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setMethod(CodeableConcept value) {
        this.method = value;
    }

}
