//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.24 at 10:24:43 PM CET 
//


package org.hl7.fhir.r4.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for AssertionOperatorType-list.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="AssertionOperatorType-list"&amp;gt;
 *   &amp;lt;restriction base="{http://hl7.org/fhir}code-primitive"&amp;gt;
 *     &amp;lt;enumeration value="equals"/&amp;gt;
 *     &amp;lt;enumeration value="notEquals"/&amp;gt;
 *     &amp;lt;enumeration value="in"/&amp;gt;
 *     &amp;lt;enumeration value="notIn"/&amp;gt;
 *     &amp;lt;enumeration value="greaterThan"/&amp;gt;
 *     &amp;lt;enumeration value="lessThan"/&amp;gt;
 *     &amp;lt;enumeration value="empty"/&amp;gt;
 *     &amp;lt;enumeration value="notEmpty"/&amp;gt;
 *     &amp;lt;enumeration value="contains"/&amp;gt;
 *     &amp;lt;enumeration value="notContains"/&amp;gt;
 *     &amp;lt;enumeration value="eval"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "AssertionOperatorType-list")
@XmlEnum
public enum AssertionOperatorTypeList {


    /**
     * equals
     * 
     */
    @XmlEnumValue("equals")
    EQUALS("equals"),

    /**
     * notEquals
     * 
     */
    @XmlEnumValue("notEquals")
    NOT_EQUALS("notEquals"),

    /**
     * in
     * 
     */
    @XmlEnumValue("in")
    IN("in"),

    /**
     * notIn
     * 
     */
    @XmlEnumValue("notIn")
    NOT_IN("notIn"),

    /**
     * greaterThan
     * 
     */
    @XmlEnumValue("greaterThan")
    GREATER_THAN("greaterThan"),

    /**
     * lessThan
     * 
     */
    @XmlEnumValue("lessThan")
    LESS_THAN("lessThan"),

    /**
     * empty
     * 
     */
    @XmlEnumValue("empty")
    EMPTY("empty"),

    /**
     * notEmpty
     * 
     */
    @XmlEnumValue("notEmpty")
    NOT_EMPTY("notEmpty"),

    /**
     * contains
     * 
     */
    @XmlEnumValue("contains")
    CONTAINS("contains"),

    /**
     * notContains
     * 
     */
    @XmlEnumValue("notContains")
    NOT_CONTAINS("notContains"),

    /**
     * evaluate
     * 
     */
    @XmlEnumValue("eval")
    EVAL("eval");
    private final java.lang.String value;

    AssertionOperatorTypeList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static AssertionOperatorTypeList fromValue(java.lang.String v) {
        for (AssertionOperatorTypeList c: AssertionOperatorTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
