//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.24 at 10:24:43 PM CET 
//


package org.hl7.fhir.r4.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Catalog entries are wrappers that contextualize items included in a catalog.
 * 
 * &lt;p&gt;Java class for CatalogEntry.RelatedEntry complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="CatalogEntry.RelatedEntry"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{http://hl7.org/fhir}BackboneElement"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="relationtype" type="{http://hl7.org/fhir}CatalogEntryRelationType"/&amp;gt;
 *         &amp;lt;element name="item" type="{http://hl7.org/fhir}Reference"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CatalogEntry.RelatedEntry", propOrder = {
    "relationtype",
    "item"
})
public class CatalogEntryRelatedEntry
    extends BackboneElement
{

    @XmlElement(required = true)
    protected CatalogEntryRelationType relationtype;
    @XmlElement(required = true)
    protected Reference item;

    /**
     * Gets the value of the relationtype property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogEntryRelationType }
     *     
     */
    public CatalogEntryRelationType getRelationtype() {
        return relationtype;
    }

    /**
     * Sets the value of the relationtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogEntryRelationType }
     *     
     */
    public void setRelationtype(CatalogEntryRelationType value) {
        this.relationtype = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setItem(Reference value) {
        this.item = value;
    }

}
