//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.24 at 10:24:43 PM CET 
//


package org.hl7.fhir.r4.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for DiscriminatorType-list.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="DiscriminatorType-list"&amp;gt;
 *   &amp;lt;restriction base="{http://hl7.org/fhir}code-primitive"&amp;gt;
 *     &amp;lt;enumeration value="value"/&amp;gt;
 *     &amp;lt;enumeration value="exists"/&amp;gt;
 *     &amp;lt;enumeration value="pattern"/&amp;gt;
 *     &amp;lt;enumeration value="type"/&amp;gt;
 *     &amp;lt;enumeration value="profile"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "DiscriminatorType-list")
@XmlEnum
public enum DiscriminatorTypeList {


    /**
     * Value
     * 
     */
    @XmlEnumValue("value")
    VALUE("value"),

    /**
     * Exists
     * 
     */
    @XmlEnumValue("exists")
    EXISTS("exists"),

    /**
     * Pattern
     * 
     */
    @XmlEnumValue("pattern")
    PATTERN("pattern"),

    /**
     * Type
     * 
     */
    @XmlEnumValue("type")
    TYPE("type"),

    /**
     * Profile
     * 
     */
    @XmlEnumValue("profile")
    PROFILE("profile");
    private final java.lang.String value;

    DiscriminatorTypeList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static DiscriminatorTypeList fromValue(java.lang.String v) {
        for (DiscriminatorTypeList c: DiscriminatorTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
