//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.24 at 10:24:43 PM CET 
//


package org.hl7.fhir.r4.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for ExpressionLanguage-list.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="ExpressionLanguage-list"&amp;gt;
 *   &amp;lt;restriction base="{http://hl7.org/fhir}code-primitive"&amp;gt;
 *     &amp;lt;enumeration value="text/cql"/&amp;gt;
 *     &amp;lt;enumeration value="text/fhirpath"/&amp;gt;
 *     &amp;lt;enumeration value="application/x-fhir-query"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "ExpressionLanguage-list")
@XmlEnum
public enum ExpressionLanguageList {


    /**
     * CQL
     * 
     */
    @XmlEnumValue("text/cql")
    TEXT_CQL("text/cql"),

    /**
     * FHIRPath
     * 
     */
    @XmlEnumValue("text/fhirpath")
    TEXT_FHIRPATH("text/fhirpath"),

    /**
     * FHIR Query
     * 
     */
    @XmlEnumValue("application/x-fhir-query")
    APPLICATION_X_FHIR_QUERY("application/x-fhir-query");
    private final java.lang.String value;

    ExpressionLanguageList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static ExpressionLanguageList fromValue(java.lang.String v) {
        for (ExpressionLanguageList c: ExpressionLanguageList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
