//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.24 at 10:24:43 PM CET 
//


package org.hl7.fhir.r4.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A formal computable definition of a graph of resources - that is, a coherent set of resources that form a graph by following references. The Graph Definition resource defines a set and makes rules about the set.
 * 
 * &lt;p&gt;Java class for GraphDefinition.Compartment complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="GraphDefinition.Compartment"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{http://hl7.org/fhir}BackboneElement"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="use" type="{http://hl7.org/fhir}GraphCompartmentUse"/&amp;gt;
 *         &amp;lt;element name="code" type="{http://hl7.org/fhir}CompartmentType"/&amp;gt;
 *         &amp;lt;element name="rule" type="{http://hl7.org/fhir}GraphCompartmentRule"/&amp;gt;
 *         &amp;lt;element name="expression" type="{http://hl7.org/fhir}string" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="description" type="{http://hl7.org/fhir}string" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GraphDefinition.Compartment", propOrder = {
    "use",
    "code",
    "rule",
    "expression",
    "description"
})
public class GraphDefinitionCompartment
    extends BackboneElement
{

    @XmlElement(required = true)
    protected GraphCompartmentUse use;
    @XmlElement(required = true)
    protected CompartmentType code;
    @XmlElement(required = true)
    protected GraphCompartmentRule rule;
    protected String expression;
    protected String description;

    /**
     * Gets the value of the use property.
     * 
     * @return
     *     possible object is
     *     {@link GraphCompartmentUse }
     *     
     */
    public GraphCompartmentUse getUse() {
        return use;
    }

    /**
     * Sets the value of the use property.
     * 
     * @param value
     *     allowed object is
     *     {@link GraphCompartmentUse }
     *     
     */
    public void setUse(GraphCompartmentUse value) {
        this.use = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link CompartmentType }
     *     
     */
    public CompartmentType getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompartmentType }
     *     
     */
    public void setCode(CompartmentType value) {
        this.code = value;
    }

    /**
     * Gets the value of the rule property.
     * 
     * @return
     *     possible object is
     *     {@link GraphCompartmentRule }
     *     
     */
    public GraphCompartmentRule getRule() {
        return rule;
    }

    /**
     * Sets the value of the rule property.
     * 
     * @param value
     *     allowed object is
     *     {@link GraphCompartmentRule }
     *     
     */
    public void setRule(GraphCompartmentRule value) {
        this.rule = value;
    }

    /**
     * Gets the value of the expression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpression() {
        return expression;
    }

    /**
     * Sets the value of the expression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpression(String value) {
        this.expression = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
