//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.24 at 10:24:43 PM CET 
//


package org.hl7.fhir.r4.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for InvoicePriceComponentType-list.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="InvoicePriceComponentType-list"&amp;gt;
 *   &amp;lt;restriction base="{http://hl7.org/fhir}code-primitive"&amp;gt;
 *     &amp;lt;enumeration value="base"/&amp;gt;
 *     &amp;lt;enumeration value="surcharge"/&amp;gt;
 *     &amp;lt;enumeration value="deduction"/&amp;gt;
 *     &amp;lt;enumeration value="discount"/&amp;gt;
 *     &amp;lt;enumeration value="tax"/&amp;gt;
 *     &amp;lt;enumeration value="informational"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "InvoicePriceComponentType-list")
@XmlEnum
public enum InvoicePriceComponentTypeList {


    /**
     * base price
     * 
     */
    @XmlEnumValue("base")
    BASE("base"),

    /**
     * surcharge
     * 
     */
    @XmlEnumValue("surcharge")
    SURCHARGE("surcharge"),

    /**
     * deduction
     * 
     */
    @XmlEnumValue("deduction")
    DEDUCTION("deduction"),

    /**
     * discount
     * 
     */
    @XmlEnumValue("discount")
    DISCOUNT("discount"),

    /**
     * tax
     * 
     */
    @XmlEnumValue("tax")
    TAX("tax"),

    /**
     * informational
     * 
     */
    @XmlEnumValue("informational")
    INFORMATIONAL("informational");
    private final java.lang.String value;

    InvoicePriceComponentTypeList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static InvoicePriceComponentTypeList fromValue(java.lang.String v) {
        for (InvoicePriceComponentTypeList c: InvoicePriceComponentTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
