//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.24 at 10:24:43 PM CET 
//


package org.hl7.fhir.r4.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * If the element is present, it must have either a &#064;value, an &#064;id, or extensions
 * 
 * &lt;p&gt;Java class for MedicinalProduct complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="MedicinalProduct"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{http://hl7.org/fhir}DomainResource"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="identifier" type="{http://hl7.org/fhir}Identifier" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="type" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="domain" type="{http://hl7.org/fhir}Coding" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="combinedPharmaceuticalDoseForm" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="legalStatusOfSupply" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="additionalMonitoringIndicator" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="specialMeasures" type="{http://hl7.org/fhir}string" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="paediatricUseIndicator" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="productClassification" type="{http://hl7.org/fhir}CodeableConcept" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="marketingStatus" type="{http://hl7.org/fhir}MarketingStatus" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="pharmaceuticalProduct" type="{http://hl7.org/fhir}Reference" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="packagedMedicinalProduct" type="{http://hl7.org/fhir}Reference" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="attachedDocument" type="{http://hl7.org/fhir}Reference" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="masterFile" type="{http://hl7.org/fhir}Reference" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="contact" type="{http://hl7.org/fhir}Reference" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="clinicalTrial" type="{http://hl7.org/fhir}Reference" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="name" type="{http://hl7.org/fhir}MedicinalProduct.Name" maxOccurs="unbounded"/&amp;gt;
 *         &amp;lt;element name="crossReference" type="{http://hl7.org/fhir}Identifier" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="manufacturingBusinessOperation" type="{http://hl7.org/fhir}MedicinalProduct.ManufacturingBusinessOperation" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="specialDesignation" type="{http://hl7.org/fhir}MedicinalProduct.SpecialDesignation" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MedicinalProduct", propOrder = {
    "identifier",
    "type",
    "domain",
    "combinedPharmaceuticalDoseForm",
    "legalStatusOfSupply",
    "additionalMonitoringIndicator",
    "specialMeasures",
    "paediatricUseIndicator",
    "productClassification",
    "marketingStatus",
    "pharmaceuticalProduct",
    "packagedMedicinalProduct",
    "attachedDocument",
    "masterFile",
    "contact",
    "clinicalTrial",
    "name",
    "crossReference",
    "manufacturingBusinessOperation",
    "specialDesignation"
})
public class MedicinalProduct
    extends DomainResource
{

    protected List<Identifier> identifier;
    protected CodeableConcept type;
    protected Coding domain;
    protected CodeableConcept combinedPharmaceuticalDoseForm;
    protected CodeableConcept legalStatusOfSupply;
    protected CodeableConcept additionalMonitoringIndicator;
    protected List<String> specialMeasures;
    protected CodeableConcept paediatricUseIndicator;
    protected List<CodeableConcept> productClassification;
    protected List<MarketingStatus> marketingStatus;
    protected List<Reference> pharmaceuticalProduct;
    protected List<Reference> packagedMedicinalProduct;
    protected List<Reference> attachedDocument;
    protected List<Reference> masterFile;
    protected List<Reference> contact;
    protected List<Reference> clinicalTrial;
    @XmlElement(required = true)
    protected List<MedicinalProductName> name;
    protected List<Identifier> crossReference;
    protected List<MedicinalProductManufacturingBusinessOperation> manufacturingBusinessOperation;
    protected List<MedicinalProductSpecialDesignation> specialDesignation;

    /**
     * Gets the value of the identifier property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the identifier property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getIdentifier().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Identifier }
     * 
     * 
     */
    public List<Identifier> getIdentifier() {
        if (identifier == null) {
            identifier = new ArrayList<Identifier>();
        }
        return this.identifier;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setType(CodeableConcept value) {
        this.type = value;
    }

    /**
     * Gets the value of the domain property.
     * 
     * @return
     *     possible object is
     *     {@link Coding }
     *     
     */
    public Coding getDomain() {
        return domain;
    }

    /**
     * Sets the value of the domain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coding }
     *     
     */
    public void setDomain(Coding value) {
        this.domain = value;
    }

    /**
     * Gets the value of the combinedPharmaceuticalDoseForm property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getCombinedPharmaceuticalDoseForm() {
        return combinedPharmaceuticalDoseForm;
    }

    /**
     * Sets the value of the combinedPharmaceuticalDoseForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setCombinedPharmaceuticalDoseForm(CodeableConcept value) {
        this.combinedPharmaceuticalDoseForm = value;
    }

    /**
     * Gets the value of the legalStatusOfSupply property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getLegalStatusOfSupply() {
        return legalStatusOfSupply;
    }

    /**
     * Sets the value of the legalStatusOfSupply property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setLegalStatusOfSupply(CodeableConcept value) {
        this.legalStatusOfSupply = value;
    }

    /**
     * Gets the value of the additionalMonitoringIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getAdditionalMonitoringIndicator() {
        return additionalMonitoringIndicator;
    }

    /**
     * Sets the value of the additionalMonitoringIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setAdditionalMonitoringIndicator(CodeableConcept value) {
        this.additionalMonitoringIndicator = value;
    }

    /**
     * Gets the value of the specialMeasures property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the specialMeasures property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getSpecialMeasures().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSpecialMeasures() {
        if (specialMeasures == null) {
            specialMeasures = new ArrayList<String>();
        }
        return this.specialMeasures;
    }

    /**
     * Gets the value of the paediatricUseIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getPaediatricUseIndicator() {
        return paediatricUseIndicator;
    }

    /**
     * Sets the value of the paediatricUseIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setPaediatricUseIndicator(CodeableConcept value) {
        this.paediatricUseIndicator = value;
    }

    /**
     * Gets the value of the productClassification property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the productClassification property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getProductClassification().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link CodeableConcept }
     * 
     * 
     */
    public List<CodeableConcept> getProductClassification() {
        if (productClassification == null) {
            productClassification = new ArrayList<CodeableConcept>();
        }
        return this.productClassification;
    }

    /**
     * Gets the value of the marketingStatus property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the marketingStatus property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getMarketingStatus().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link MarketingStatus }
     * 
     * 
     */
    public List<MarketingStatus> getMarketingStatus() {
        if (marketingStatus == null) {
            marketingStatus = new ArrayList<MarketingStatus>();
        }
        return this.marketingStatus;
    }

    /**
     * Gets the value of the pharmaceuticalProduct property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the pharmaceuticalProduct property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getPharmaceuticalProduct().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getPharmaceuticalProduct() {
        if (pharmaceuticalProduct == null) {
            pharmaceuticalProduct = new ArrayList<Reference>();
        }
        return this.pharmaceuticalProduct;
    }

    /**
     * Gets the value of the packagedMedicinalProduct property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the packagedMedicinalProduct property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getPackagedMedicinalProduct().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getPackagedMedicinalProduct() {
        if (packagedMedicinalProduct == null) {
            packagedMedicinalProduct = new ArrayList<Reference>();
        }
        return this.packagedMedicinalProduct;
    }

    /**
     * Gets the value of the attachedDocument property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the attachedDocument property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getAttachedDocument().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getAttachedDocument() {
        if (attachedDocument == null) {
            attachedDocument = new ArrayList<Reference>();
        }
        return this.attachedDocument;
    }

    /**
     * Gets the value of the masterFile property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the masterFile property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getMasterFile().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getMasterFile() {
        if (masterFile == null) {
            masterFile = new ArrayList<Reference>();
        }
        return this.masterFile;
    }

    /**
     * Gets the value of the contact property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the contact property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getContact().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getContact() {
        if (contact == null) {
            contact = new ArrayList<Reference>();
        }
        return this.contact;
    }

    /**
     * Gets the value of the clinicalTrial property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the clinicalTrial property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getClinicalTrial().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getClinicalTrial() {
        if (clinicalTrial == null) {
            clinicalTrial = new ArrayList<Reference>();
        }
        return this.clinicalTrial;
    }

    /**
     * Gets the value of the name property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the name property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getName().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link MedicinalProductName }
     * 
     * 
     */
    public List<MedicinalProductName> getName() {
        if (name == null) {
            name = new ArrayList<MedicinalProductName>();
        }
        return this.name;
    }

    /**
     * Gets the value of the crossReference property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the crossReference property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getCrossReference().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Identifier }
     * 
     * 
     */
    public List<Identifier> getCrossReference() {
        if (crossReference == null) {
            crossReference = new ArrayList<Identifier>();
        }
        return this.crossReference;
    }

    /**
     * Gets the value of the manufacturingBusinessOperation property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the manufacturingBusinessOperation property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getManufacturingBusinessOperation().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link MedicinalProductManufacturingBusinessOperation }
     * 
     * 
     */
    public List<MedicinalProductManufacturingBusinessOperation> getManufacturingBusinessOperation() {
        if (manufacturingBusinessOperation == null) {
            manufacturingBusinessOperation = new ArrayList<MedicinalProductManufacturingBusinessOperation>();
        }
        return this.manufacturingBusinessOperation;
    }

    /**
     * Gets the value of the specialDesignation property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the specialDesignation property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getSpecialDesignation().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link MedicinalProductSpecialDesignation }
     * 
     * 
     */
    public List<MedicinalProductSpecialDesignation> getSpecialDesignation() {
        if (specialDesignation == null) {
            specialDesignation = new ArrayList<MedicinalProductSpecialDesignation>();
        }
        return this.specialDesignation;
    }

}
