//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.24 at 10:24:43 PM CET 
//


package org.hl7.fhir.r4.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A medicinal product in a container or package.
 * 
 * &lt;p&gt;Java class for MedicinalProductPackaged.PackageItem complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="MedicinalProductPackaged.PackageItem"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{http://hl7.org/fhir}BackboneElement"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="identifier" type="{http://hl7.org/fhir}Identifier" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="type" type="{http://hl7.org/fhir}CodeableConcept"/&amp;gt;
 *         &amp;lt;element name="quantity" type="{http://hl7.org/fhir}Quantity"/&amp;gt;
 *         &amp;lt;element name="material" type="{http://hl7.org/fhir}CodeableConcept" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="alternateMaterial" type="{http://hl7.org/fhir}CodeableConcept" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="device" type="{http://hl7.org/fhir}Reference" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="manufacturedItem" type="{http://hl7.org/fhir}Reference" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="packageItem" type="{http://hl7.org/fhir}MedicinalProductPackaged.PackageItem" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="physicalCharacteristics" type="{http://hl7.org/fhir}ProdCharacteristic" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="otherCharacteristics" type="{http://hl7.org/fhir}CodeableConcept" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="shelfLifeStorage" type="{http://hl7.org/fhir}ProductShelfLife" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="manufacturer" type="{http://hl7.org/fhir}Reference" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MedicinalProductPackaged.PackageItem", propOrder = {
    "identifier",
    "type",
    "quantity",
    "material",
    "alternateMaterial",
    "device",
    "manufacturedItem",
    "packageItem",
    "physicalCharacteristics",
    "otherCharacteristics",
    "shelfLifeStorage",
    "manufacturer"
})
public class MedicinalProductPackagedPackageItem
    extends BackboneElement
{

    protected List<Identifier> identifier;
    @XmlElement(required = true)
    protected CodeableConcept type;
    @XmlElement(required = true)
    protected Quantity quantity;
    protected List<CodeableConcept> material;
    protected List<CodeableConcept> alternateMaterial;
    protected List<Reference> device;
    protected List<Reference> manufacturedItem;
    protected List<MedicinalProductPackagedPackageItem> packageItem;
    protected ProdCharacteristic physicalCharacteristics;
    protected List<CodeableConcept> otherCharacteristics;
    protected List<ProductShelfLife> shelfLifeStorage;
    protected List<Reference> manufacturer;

    /**
     * Gets the value of the identifier property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the identifier property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getIdentifier().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Identifier }
     * 
     * 
     */
    public List<Identifier> getIdentifier() {
        if (identifier == null) {
            identifier = new ArrayList<Identifier>();
        }
        return this.identifier;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setType(CodeableConcept value) {
        this.type = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setQuantity(Quantity value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the material property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the material property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getMaterial().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link CodeableConcept }
     * 
     * 
     */
    public List<CodeableConcept> getMaterial() {
        if (material == null) {
            material = new ArrayList<CodeableConcept>();
        }
        return this.material;
    }

    /**
     * Gets the value of the alternateMaterial property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the alternateMaterial property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getAlternateMaterial().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link CodeableConcept }
     * 
     * 
     */
    public List<CodeableConcept> getAlternateMaterial() {
        if (alternateMaterial == null) {
            alternateMaterial = new ArrayList<CodeableConcept>();
        }
        return this.alternateMaterial;
    }

    /**
     * Gets the value of the device property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the device property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getDevice().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getDevice() {
        if (device == null) {
            device = new ArrayList<Reference>();
        }
        return this.device;
    }

    /**
     * Gets the value of the manufacturedItem property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the manufacturedItem property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getManufacturedItem().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getManufacturedItem() {
        if (manufacturedItem == null) {
            manufacturedItem = new ArrayList<Reference>();
        }
        return this.manufacturedItem;
    }

    /**
     * Gets the value of the packageItem property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the packageItem property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getPackageItem().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link MedicinalProductPackagedPackageItem }
     * 
     * 
     */
    public List<MedicinalProductPackagedPackageItem> getPackageItem() {
        if (packageItem == null) {
            packageItem = new ArrayList<MedicinalProductPackagedPackageItem>();
        }
        return this.packageItem;
    }

    /**
     * Gets the value of the physicalCharacteristics property.
     * 
     * @return
     *     possible object is
     *     {@link ProdCharacteristic }
     *     
     */
    public ProdCharacteristic getPhysicalCharacteristics() {
        return physicalCharacteristics;
    }

    /**
     * Sets the value of the physicalCharacteristics property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProdCharacteristic }
     *     
     */
    public void setPhysicalCharacteristics(ProdCharacteristic value) {
        this.physicalCharacteristics = value;
    }

    /**
     * Gets the value of the otherCharacteristics property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the otherCharacteristics property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getOtherCharacteristics().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link CodeableConcept }
     * 
     * 
     */
    public List<CodeableConcept> getOtherCharacteristics() {
        if (otherCharacteristics == null) {
            otherCharacteristics = new ArrayList<CodeableConcept>();
        }
        return this.otherCharacteristics;
    }

    /**
     * Gets the value of the shelfLifeStorage property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the shelfLifeStorage property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getShelfLifeStorage().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link ProductShelfLife }
     * 
     * 
     */
    public List<ProductShelfLife> getShelfLifeStorage() {
        if (shelfLifeStorage == null) {
            shelfLifeStorage = new ArrayList<ProductShelfLife>();
        }
        return this.shelfLifeStorage;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the manufacturer property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getManufacturer().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getManufacturer() {
        if (manufacturer == null) {
            manufacturer = new ArrayList<Reference>();
        }
        return this.manufacturer;
    }

}
