//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.24 at 10:24:43 PM CET 
//


package org.hl7.fhir.r4.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * If the element is present, it must have either a &#064;value, an &#064;id, or extensions
 * 
 * &lt;p&gt;Java class for MedicinalProductContraindication complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="MedicinalProductContraindication"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{http://hl7.org/fhir}DomainResource"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="subject" type="{http://hl7.org/fhir}Reference" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="disease" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="diseaseStatus" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="comorbidity" type="{http://hl7.org/fhir}CodeableConcept" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="therapeuticIndication" type="{http://hl7.org/fhir}Reference" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="otherTherapy" type="{http://hl7.org/fhir}MedicinalProductContraindication.OtherTherapy" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="population" type="{http://hl7.org/fhir}Population" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MedicinalProductContraindication", propOrder = {
    "subject",
    "disease",
    "diseaseStatus",
    "comorbidity",
    "therapeuticIndication",
    "otherTherapy",
    "population"
})
public class MedicinalProductContraindication
    extends DomainResource
{

    protected List<Reference> subject;
    protected CodeableConcept disease;
    protected CodeableConcept diseaseStatus;
    protected List<CodeableConcept> comorbidity;
    protected List<Reference> therapeuticIndication;
    protected List<MedicinalProductContraindicationOtherTherapy> otherTherapy;
    protected List<Population> population;

    /**
     * Gets the value of the subject property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the subject property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getSubject().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getSubject() {
        if (subject == null) {
            subject = new ArrayList<Reference>();
        }
        return this.subject;
    }

    /**
     * Gets the value of the disease property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getDisease() {
        return disease;
    }

    /**
     * Sets the value of the disease property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setDisease(CodeableConcept value) {
        this.disease = value;
    }

    /**
     * Gets the value of the diseaseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getDiseaseStatus() {
        return diseaseStatus;
    }

    /**
     * Sets the value of the diseaseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setDiseaseStatus(CodeableConcept value) {
        this.diseaseStatus = value;
    }

    /**
     * Gets the value of the comorbidity property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the comorbidity property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getComorbidity().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link CodeableConcept }
     * 
     * 
     */
    public List<CodeableConcept> getComorbidity() {
        if (comorbidity == null) {
            comorbidity = new ArrayList<CodeableConcept>();
        }
        return this.comorbidity;
    }

    /**
     * Gets the value of the therapeuticIndication property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the therapeuticIndication property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getTherapeuticIndication().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getTherapeuticIndication() {
        if (therapeuticIndication == null) {
            therapeuticIndication = new ArrayList<Reference>();
        }
        return this.therapeuticIndication;
    }

    /**
     * Gets the value of the otherTherapy property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the otherTherapy property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getOtherTherapy().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link MedicinalProductContraindicationOtherTherapy }
     * 
     * 
     */
    public List<MedicinalProductContraindicationOtherTherapy> getOtherTherapy() {
        if (otherTherapy == null) {
            otherTherapy = new ArrayList<MedicinalProductContraindicationOtherTherapy>();
        }
        return this.otherTherapy;
    }

    /**
     * Gets the value of the population property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the population property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getPopulation().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Population }
     * 
     * 
     */
    public List<Population> getPopulation() {
        if (population == null) {
            population = new ArrayList<Population>();
        }
        return this.population;
    }

}
