//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.24 at 10:24:43 PM CET 
//


package org.hl7.fhir.r4.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * If the element is present, it must have either a &#064;value, an &#064;id, or extensions
 * 
 * &lt;p&gt;Java class for MedicinalProductAuthorization complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="MedicinalProductAuthorization"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{http://hl7.org/fhir}DomainResource"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="identifier" type="{http://hl7.org/fhir}Identifier" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="subject" type="{http://hl7.org/fhir}Reference" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="country" type="{http://hl7.org/fhir}CodeableConcept" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="jurisdiction" type="{http://hl7.org/fhir}CodeableConcept" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="status" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="statusDate" type="{http://hl7.org/fhir}dateTime" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="restoreDate" type="{http://hl7.org/fhir}dateTime" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="validityPeriod" type="{http://hl7.org/fhir}Period" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="dataExclusivityPeriod" type="{http://hl7.org/fhir}Period" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="dateOfFirstAuthorization" type="{http://hl7.org/fhir}dateTime" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="internationalBirthDate" type="{http://hl7.org/fhir}dateTime" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="legalBasis" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="jurisdictionalAuthorization" type="{http://hl7.org/fhir}MedicinalProductAuthorization.JurisdictionalAuthorization" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="holder" type="{http://hl7.org/fhir}Reference" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="regulator" type="{http://hl7.org/fhir}Reference" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="procedure" type="{http://hl7.org/fhir}MedicinalProductAuthorization.Procedure" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MedicinalProductAuthorization", propOrder = {
    "identifier",
    "subject",
    "country",
    "jurisdiction",
    "status",
    "statusDate",
    "restoreDate",
    "validityPeriod",
    "dataExclusivityPeriod",
    "dateOfFirstAuthorization",
    "internationalBirthDate",
    "legalBasis",
    "jurisdictionalAuthorization",
    "holder",
    "regulator",
    "procedure"
})
public class MedicinalProductAuthorization
    extends DomainResource
{

    protected List<Identifier> identifier;
    protected Reference subject;
    protected List<CodeableConcept> country;
    protected List<CodeableConcept> jurisdiction;
    protected CodeableConcept status;
    protected DateTime statusDate;
    protected DateTime restoreDate;
    protected Period validityPeriod;
    protected Period dataExclusivityPeriod;
    protected DateTime dateOfFirstAuthorization;
    protected DateTime internationalBirthDate;
    protected CodeableConcept legalBasis;
    protected List<MedicinalProductAuthorizationJurisdictionalAuthorization> jurisdictionalAuthorization;
    protected Reference holder;
    protected Reference regulator;
    protected MedicinalProductAuthorizationProcedure procedure;

    /**
     * Gets the value of the identifier property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the identifier property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getIdentifier().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Identifier }
     * 
     * 
     */
    public List<Identifier> getIdentifier() {
        if (identifier == null) {
            identifier = new ArrayList<Identifier>();
        }
        return this.identifier;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setSubject(Reference value) {
        this.subject = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the country property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getCountry().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link CodeableConcept }
     * 
     * 
     */
    public List<CodeableConcept> getCountry() {
        if (country == null) {
            country = new ArrayList<CodeableConcept>();
        }
        return this.country;
    }

    /**
     * Gets the value of the jurisdiction property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the jurisdiction property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getJurisdiction().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link CodeableConcept }
     * 
     * 
     */
    public List<CodeableConcept> getJurisdiction() {
        if (jurisdiction == null) {
            jurisdiction = new ArrayList<CodeableConcept>();
        }
        return this.jurisdiction;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setStatus(CodeableConcept value) {
        this.status = value;
    }

    /**
     * Gets the value of the statusDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getStatusDate() {
        return statusDate;
    }

    /**
     * Sets the value of the statusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setStatusDate(DateTime value) {
        this.statusDate = value;
    }

    /**
     * Gets the value of the restoreDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getRestoreDate() {
        return restoreDate;
    }

    /**
     * Sets the value of the restoreDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setRestoreDate(DateTime value) {
        this.restoreDate = value;
    }

    /**
     * Gets the value of the validityPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getValidityPeriod() {
        return validityPeriod;
    }

    /**
     * Sets the value of the validityPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setValidityPeriod(Period value) {
        this.validityPeriod = value;
    }

    /**
     * Gets the value of the dataExclusivityPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getDataExclusivityPeriod() {
        return dataExclusivityPeriod;
    }

    /**
     * Sets the value of the dataExclusivityPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setDataExclusivityPeriod(Period value) {
        this.dataExclusivityPeriod = value;
    }

    /**
     * Gets the value of the dateOfFirstAuthorization property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getDateOfFirstAuthorization() {
        return dateOfFirstAuthorization;
    }

    /**
     * Sets the value of the dateOfFirstAuthorization property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setDateOfFirstAuthorization(DateTime value) {
        this.dateOfFirstAuthorization = value;
    }

    /**
     * Gets the value of the internationalBirthDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getInternationalBirthDate() {
        return internationalBirthDate;
    }

    /**
     * Sets the value of the internationalBirthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setInternationalBirthDate(DateTime value) {
        this.internationalBirthDate = value;
    }

    /**
     * Gets the value of the legalBasis property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getLegalBasis() {
        return legalBasis;
    }

    /**
     * Sets the value of the legalBasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setLegalBasis(CodeableConcept value) {
        this.legalBasis = value;
    }

    /**
     * Gets the value of the jurisdictionalAuthorization property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the jurisdictionalAuthorization property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getJurisdictionalAuthorization().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link MedicinalProductAuthorizationJurisdictionalAuthorization }
     * 
     * 
     */
    public List<MedicinalProductAuthorizationJurisdictionalAuthorization> getJurisdictionalAuthorization() {
        if (jurisdictionalAuthorization == null) {
            jurisdictionalAuthorization = new ArrayList<MedicinalProductAuthorizationJurisdictionalAuthorization>();
        }
        return this.jurisdictionalAuthorization;
    }

    /**
     * Gets the value of the holder property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getHolder() {
        return holder;
    }

    /**
     * Sets the value of the holder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setHolder(Reference value) {
        this.holder = value;
    }

    /**
     * Gets the value of the regulator property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getRegulator() {
        return regulator;
    }

    /**
     * Sets the value of the regulator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setRegulator(Reference value) {
        this.regulator = value;
    }

    /**
     * Gets the value of the procedure property.
     * 
     * @return
     *     possible object is
     *     {@link MedicinalProductAuthorizationProcedure }
     *     
     */
    public MedicinalProductAuthorizationProcedure getProcedure() {
        return procedure;
    }

    /**
     * Sets the value of the procedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link MedicinalProductAuthorizationProcedure }
     *     
     */
    public void setProcedure(MedicinalProductAuthorizationProcedure value) {
        this.procedure = value;
    }

}
