//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.24 at 10:24:43 PM CET 
//


package org.hl7.fhir.r4.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for ObservationDataType-list.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="ObservationDataType-list"&amp;gt;
 *   &amp;lt;restriction base="{http://hl7.org/fhir}code-primitive"&amp;gt;
 *     &amp;lt;enumeration value="Quantity"/&amp;gt;
 *     &amp;lt;enumeration value="CodeableConcept"/&amp;gt;
 *     &amp;lt;enumeration value="string"/&amp;gt;
 *     &amp;lt;enumeration value="boolean"/&amp;gt;
 *     &amp;lt;enumeration value="integer"/&amp;gt;
 *     &amp;lt;enumeration value="Range"/&amp;gt;
 *     &amp;lt;enumeration value="Ratio"/&amp;gt;
 *     &amp;lt;enumeration value="SampledData"/&amp;gt;
 *     &amp;lt;enumeration value="time"/&amp;gt;
 *     &amp;lt;enumeration value="dateTime"/&amp;gt;
 *     &amp;lt;enumeration value="Period"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "ObservationDataType-list")
@XmlEnum
public enum ObservationDataTypeList {


    /**
     * Quantity
     * 
     */
    @XmlEnumValue("Quantity")
    QUANTITY("Quantity"),

    /**
     * CodeableConcept
     * 
     */
    @XmlEnumValue("CodeableConcept")
    CODEABLE_CONCEPT("CodeableConcept"),

    /**
     * string
     * 
     */
    @XmlEnumValue("string")
    STRING("string"),

    /**
     * boolean
     * 
     */
    @XmlEnumValue("boolean")
    BOOLEAN("boolean"),

    /**
     * integer
     * 
     */
    @XmlEnumValue("integer")
    INTEGER("integer"),

    /**
     * Range
     * 
     */
    @XmlEnumValue("Range")
    RANGE("Range"),

    /**
     * Ratio
     * 
     */
    @XmlEnumValue("Ratio")
    RATIO("Ratio"),

    /**
     * SampledData
     * 
     */
    @XmlEnumValue("SampledData")
    SAMPLED_DATA("SampledData"),

    /**
     * time
     * 
     */
    @XmlEnumValue("time")
    TIME("time"),

    /**
     * dateTime
     * 
     */
    @XmlEnumValue("dateTime")
    DATE_TIME("dateTime"),

    /**
     * Period
     * 
     */
    @XmlEnumValue("Period")
    PERIOD("Period");
    private final java.lang.String value;

    ObservationDataTypeList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static ObservationDataTypeList fromValue(java.lang.String v) {
        for (ObservationDataTypeList c: ObservationDataTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
