//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.24 at 10:24:43 PM CET 
//


package org.hl7.fhir.r4.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Set of definitional characteristics for a kind of observation or measurement produced or consumed by an orderable health care service.
 * 
 * &lt;p&gt;Java class for ObservationDefinition.QualifiedInterval complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="ObservationDefinition.QualifiedInterval"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{http://hl7.org/fhir}BackboneElement"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="category" type="{http://hl7.org/fhir}ObservationRangeCategory" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="range" type="{http://hl7.org/fhir}Range" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="context" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="appliesTo" type="{http://hl7.org/fhir}CodeableConcept" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="gender" type="{http://hl7.org/fhir}AdministrativeGender" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="age" type="{http://hl7.org/fhir}Range" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="gestationalAge" type="{http://hl7.org/fhir}Range" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="condition" type="{http://hl7.org/fhir}string" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObservationDefinition.QualifiedInterval", propOrder = {
    "category",
    "range",
    "context",
    "appliesTo",
    "gender",
    "age",
    "gestationalAge",
    "condition"
})
public class ObservationDefinitionQualifiedInterval
    extends BackboneElement
{

    protected ObservationRangeCategory category;
    protected Range range;
    protected CodeableConcept context;
    protected List<CodeableConcept> appliesTo;
    protected AdministrativeGender gender;
    protected Range age;
    protected Range gestationalAge;
    protected String condition;

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link ObservationRangeCategory }
     *     
     */
    public ObservationRangeCategory getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObservationRangeCategory }
     *     
     */
    public void setCategory(ObservationRangeCategory value) {
        this.category = value;
    }

    /**
     * Gets the value of the range property.
     * 
     * @return
     *     possible object is
     *     {@link Range }
     *     
     */
    public Range getRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     * 
     * @param value
     *     allowed object is
     *     {@link Range }
     *     
     */
    public void setRange(Range value) {
        this.range = value;
    }

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setContext(CodeableConcept value) {
        this.context = value;
    }

    /**
     * Gets the value of the appliesTo property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the appliesTo property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getAppliesTo().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link CodeableConcept }
     * 
     * 
     */
    public List<CodeableConcept> getAppliesTo() {
        if (appliesTo == null) {
            appliesTo = new ArrayList<CodeableConcept>();
        }
        return this.appliesTo;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link AdministrativeGender }
     *     
     */
    public AdministrativeGender getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdministrativeGender }
     *     
     */
    public void setGender(AdministrativeGender value) {
        this.gender = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link Range }
     *     
     */
    public Range getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link Range }
     *     
     */
    public void setAge(Range value) {
        this.age = value;
    }

    /**
     * Gets the value of the gestationalAge property.
     * 
     * @return
     *     possible object is
     *     {@link Range }
     *     
     */
    public Range getGestationalAge() {
        return gestationalAge;
    }

    /**
     * Sets the value of the gestationalAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Range }
     *     
     */
    public void setGestationalAge(Range value) {
        this.gestationalAge = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCondition(String value) {
        this.condition = value;
    }

}
