//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.24 at 10:24:43 PM CET 
//


package org.hl7.fhir.r4.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * If the element is present, it must have a value for at least one of the defined elements, an &#064;id referenced from the Narrative, or extensions
 * 
 * &lt;p&gt;Java class for Population complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="Population"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{http://hl7.org/fhir}BackboneElement"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;choice minOccurs="0"&amp;gt;
 *           &amp;lt;element name="ageRange" type="{http://hl7.org/fhir}Range"/&amp;gt;
 *           &amp;lt;element name="ageCodeableConcept" type="{http://hl7.org/fhir}CodeableConcept"/&amp;gt;
 *         &amp;lt;/choice&amp;gt;
 *         &amp;lt;element name="gender" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="race" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="physiologicalCondition" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Population", propOrder = {
    "ageRange",
    "ageCodeableConcept",
    "gender",
    "race",
    "physiologicalCondition"
})
public class Population
    extends BackboneElement
{

    protected Range ageRange;
    protected CodeableConcept ageCodeableConcept;
    protected CodeableConcept gender;
    protected CodeableConcept race;
    protected CodeableConcept physiologicalCondition;

    /**
     * Gets the value of the ageRange property.
     * 
     * @return
     *     possible object is
     *     {@link Range }
     *     
     */
    public Range getAgeRange() {
        return ageRange;
    }

    /**
     * Sets the value of the ageRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Range }
     *     
     */
    public void setAgeRange(Range value) {
        this.ageRange = value;
    }

    /**
     * Gets the value of the ageCodeableConcept property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getAgeCodeableConcept() {
        return ageCodeableConcept;
    }

    /**
     * Sets the value of the ageCodeableConcept property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setAgeCodeableConcept(CodeableConcept value) {
        this.ageCodeableConcept = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setGender(CodeableConcept value) {
        this.gender = value;
    }

    /**
     * Gets the value of the race property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getRace() {
        return race;
    }

    /**
     * Sets the value of the race property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setRace(CodeableConcept value) {
        this.race = value;
    }

    /**
     * Gets the value of the physiologicalCondition property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getPhysiologicalCondition() {
        return physiologicalCondition;
    }

    /**
     * Sets the value of the physiologicalCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setPhysiologicalCondition(CodeableConcept value) {
        this.physiologicalCondition = value;
    }

}
