//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.24 at 10:24:43 PM CET 
//


package org.hl7.fhir.r4.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * If the element is present, it must have a value for at least one of the defined elements, an &#064;id referenced from the Narrative, or extensions
 * 
 * &lt;p&gt;Java class for ProdCharacteristic complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="ProdCharacteristic"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{http://hl7.org/fhir}BackboneElement"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="height" type="{http://hl7.org/fhir}Quantity" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="width" type="{http://hl7.org/fhir}Quantity" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="depth" type="{http://hl7.org/fhir}Quantity" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="weight" type="{http://hl7.org/fhir}Quantity" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="nominalVolume" type="{http://hl7.org/fhir}Quantity" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="externalDiameter" type="{http://hl7.org/fhir}Quantity" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="shape" type="{http://hl7.org/fhir}string" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="color" type="{http://hl7.org/fhir}string" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="imprint" type="{http://hl7.org/fhir}string" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="image" type="{http://hl7.org/fhir}Attachment" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="scoring" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProdCharacteristic", propOrder = {
    "height",
    "width",
    "depth",
    "weight",
    "nominalVolume",
    "externalDiameter",
    "shape",
    "color",
    "imprint",
    "image",
    "scoring"
})
public class ProdCharacteristic
    extends BackboneElement
{

    protected Quantity height;
    protected Quantity width;
    protected Quantity depth;
    protected Quantity weight;
    protected Quantity nominalVolume;
    protected Quantity externalDiameter;
    protected String shape;
    protected List<String> color;
    protected List<String> imprint;
    protected List<Attachment> image;
    protected CodeableConcept scoring;

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setHeight(Quantity value) {
        this.height = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setWidth(Quantity value) {
        this.width = value;
    }

    /**
     * Gets the value of the depth property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getDepth() {
        return depth;
    }

    /**
     * Sets the value of the depth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setDepth(Quantity value) {
        this.depth = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setWeight(Quantity value) {
        this.weight = value;
    }

    /**
     * Gets the value of the nominalVolume property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getNominalVolume() {
        return nominalVolume;
    }

    /**
     * Sets the value of the nominalVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setNominalVolume(Quantity value) {
        this.nominalVolume = value;
    }

    /**
     * Gets the value of the externalDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getExternalDiameter() {
        return externalDiameter;
    }

    /**
     * Sets the value of the externalDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setExternalDiameter(Quantity value) {
        this.externalDiameter = value;
    }

    /**
     * Gets the value of the shape property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShape() {
        return shape;
    }

    /**
     * Sets the value of the shape property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShape(String value) {
        this.shape = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the color property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getColor().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getColor() {
        if (color == null) {
            color = new ArrayList<String>();
        }
        return this.color;
    }

    /**
     * Gets the value of the imprint property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the imprint property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getImprint().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getImprint() {
        if (imprint == null) {
            imprint = new ArrayList<String>();
        }
        return this.imprint;
    }

    /**
     * Gets the value of the image property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the image property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getImage().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Attachment }
     * 
     * 
     */
    public List<Attachment> getImage() {
        if (image == null) {
            image = new ArrayList<Attachment>();
        }
        return this.image;
    }

    /**
     * Gets the value of the scoring property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getScoring() {
        return scoring;
    }

    /**
     * Sets the value of the scoring property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setScoring(CodeableConcept value) {
        this.scoring = value;
    }

}
