//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.24 at 10:24:43 PM CET 
//


package org.hl7.fhir.r4.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for RequestResourceType-list.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="RequestResourceType-list"&amp;gt;
 *   &amp;lt;restriction base="{http://hl7.org/fhir}code-primitive"&amp;gt;
 *     &amp;lt;enumeration value="Appointment"/&amp;gt;
 *     &amp;lt;enumeration value="AppointmentResponse"/&amp;gt;
 *     &amp;lt;enumeration value="CarePlan"/&amp;gt;
 *     &amp;lt;enumeration value="Claim"/&amp;gt;
 *     &amp;lt;enumeration value="CommunicationRequest"/&amp;gt;
 *     &amp;lt;enumeration value="Contract"/&amp;gt;
 *     &amp;lt;enumeration value="DeviceRequest"/&amp;gt;
 *     &amp;lt;enumeration value="EnrollmentRequest"/&amp;gt;
 *     &amp;lt;enumeration value="ImmunizationRecommendation"/&amp;gt;
 *     &amp;lt;enumeration value="MedicationRequest"/&amp;gt;
 *     &amp;lt;enumeration value="NutritionOrder"/&amp;gt;
 *     &amp;lt;enumeration value="ServiceRequest"/&amp;gt;
 *     &amp;lt;enumeration value="SupplyRequest"/&amp;gt;
 *     &amp;lt;enumeration value="Task"/&amp;gt;
 *     &amp;lt;enumeration value="VisionPrescription"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "RequestResourceType-list")
@XmlEnum
public enum RequestResourceTypeList {


    /**
     * Appointment
     * 
     */
    @XmlEnumValue("Appointment")
    APPOINTMENT("Appointment"),

    /**
     * AppointmentResponse
     * 
     */
    @XmlEnumValue("AppointmentResponse")
    APPOINTMENT_RESPONSE("AppointmentResponse"),

    /**
     * CarePlan
     * 
     */
    @XmlEnumValue("CarePlan")
    CARE_PLAN("CarePlan"),

    /**
     * Claim
     * 
     */
    @XmlEnumValue("Claim")
    CLAIM("Claim"),

    /**
     * CommunicationRequest
     * 
     */
    @XmlEnumValue("CommunicationRequest")
    COMMUNICATION_REQUEST("CommunicationRequest"),

    /**
     * Contract
     * 
     */
    @XmlEnumValue("Contract")
    CONTRACT("Contract"),

    /**
     * DeviceRequest
     * 
     */
    @XmlEnumValue("DeviceRequest")
    DEVICE_REQUEST("DeviceRequest"),

    /**
     * EnrollmentRequest
     * 
     */
    @XmlEnumValue("EnrollmentRequest")
    ENROLLMENT_REQUEST("EnrollmentRequest"),

    /**
     * ImmunizationRecommendation
     * 
     */
    @XmlEnumValue("ImmunizationRecommendation")
    IMMUNIZATION_RECOMMENDATION("ImmunizationRecommendation"),

    /**
     * MedicationRequest
     * 
     */
    @XmlEnumValue("MedicationRequest")
    MEDICATION_REQUEST("MedicationRequest"),

    /**
     * NutritionOrder
     * 
     */
    @XmlEnumValue("NutritionOrder")
    NUTRITION_ORDER("NutritionOrder"),

    /**
     * ServiceRequest
     * 
     */
    @XmlEnumValue("ServiceRequest")
    SERVICE_REQUEST("ServiceRequest"),

    /**
     * SupplyRequest
     * 
     */
    @XmlEnumValue("SupplyRequest")
    SUPPLY_REQUEST("SupplyRequest"),

    /**
     * Task
     * 
     */
    @XmlEnumValue("Task")
    TASK("Task"),

    /**
     * VisionPrescription
     * 
     */
    @XmlEnumValue("VisionPrescription")
    VISION_PRESCRIPTION("VisionPrescription");
    private final java.lang.String value;

    RequestResourceTypeList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static RequestResourceTypeList fromValue(java.lang.String v) {
        for (RequestResourceTypeList c: RequestResourceTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
