//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.24 at 10:24:43 PM CET 
//


package org.hl7.fhir.r4.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for ResearchSubjectStatus-list.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="ResearchSubjectStatus-list"&amp;gt;
 *   &amp;lt;restriction base="{http://hl7.org/fhir}code-primitive"&amp;gt;
 *     &amp;lt;enumeration value="candidate"/&amp;gt;
 *     &amp;lt;enumeration value="eligible"/&amp;gt;
 *     &amp;lt;enumeration value="follow-up"/&amp;gt;
 *     &amp;lt;enumeration value="ineligible"/&amp;gt;
 *     &amp;lt;enumeration value="not-registered"/&amp;gt;
 *     &amp;lt;enumeration value="off-study"/&amp;gt;
 *     &amp;lt;enumeration value="on-study"/&amp;gt;
 *     &amp;lt;enumeration value="on-study-intervention"/&amp;gt;
 *     &amp;lt;enumeration value="on-study-observation"/&amp;gt;
 *     &amp;lt;enumeration value="pending-on-study"/&amp;gt;
 *     &amp;lt;enumeration value="potential-candidate"/&amp;gt;
 *     &amp;lt;enumeration value="screening"/&amp;gt;
 *     &amp;lt;enumeration value="withdrawn"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "ResearchSubjectStatus-list")
@XmlEnum
public enum ResearchSubjectStatusList {


    /**
     * Candidate
     * 
     */
    @XmlEnumValue("candidate")
    CANDIDATE("candidate"),

    /**
     * Eligible
     * 
     */
    @XmlEnumValue("eligible")
    ELIGIBLE("eligible"),

    /**
     * Follow-up
     * 
     */
    @XmlEnumValue("follow-up")
    FOLLOW_UP("follow-up"),

    /**
     * Ineligible
     * 
     */
    @XmlEnumValue("ineligible")
    INELIGIBLE("ineligible"),

    /**
     * Not Registered
     * 
     */
    @XmlEnumValue("not-registered")
    NOT_REGISTERED("not-registered"),

    /**
     * Off-study
     * 
     */
    @XmlEnumValue("off-study")
    OFF_STUDY("off-study"),

    /**
     * On-study
     * 
     */
    @XmlEnumValue("on-study")
    ON_STUDY("on-study"),

    /**
     * On-study-intervention
     * 
     */
    @XmlEnumValue("on-study-intervention")
    ON_STUDY_INTERVENTION("on-study-intervention"),

    /**
     * On-study-observation
     * 
     */
    @XmlEnumValue("on-study-observation")
    ON_STUDY_OBSERVATION("on-study-observation"),

    /**
     * Pending on-study
     * 
     */
    @XmlEnumValue("pending-on-study")
    PENDING_ON_STUDY("pending-on-study"),

    /**
     * Potential Candidate
     * 
     */
    @XmlEnumValue("potential-candidate")
    POTENTIAL_CANDIDATE("potential-candidate"),

    /**
     * Screening
     * 
     */
    @XmlEnumValue("screening")
    SCREENING("screening"),

    /**
     * Withdrawn
     * 
     */
    @XmlEnumValue("withdrawn")
    WITHDRAWN("withdrawn");
    private final java.lang.String value;

    ResearchSubjectStatusList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static ResearchSubjectStatusList fromValue(java.lang.String v) {
        for (ResearchSubjectStatusList c: ResearchSubjectStatusList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
