//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.24 at 10:24:43 PM CET 
//


package org.hl7.fhir.r4.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for SystemRestfulInteraction-list.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="SystemRestfulInteraction-list"&amp;gt;
 *   &amp;lt;restriction base="{http://hl7.org/fhir}code-primitive"&amp;gt;
 *     &amp;lt;enumeration value="transaction"/&amp;gt;
 *     &amp;lt;enumeration value="batch"/&amp;gt;
 *     &amp;lt;enumeration value="search-system"/&amp;gt;
 *     &amp;lt;enumeration value="history-system"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "SystemRestfulInteraction-list")
@XmlEnum
public enum SystemRestfulInteractionList {


    /**
     * transaction
     * 
     */
    @XmlEnumValue("transaction")
    TRANSACTION("transaction"),

    /**
     * batch
     * 
     */
    @XmlEnumValue("batch")
    BATCH("batch"),

    /**
     * search-system
     * 
     */
    @XmlEnumValue("search-system")
    SEARCH_SYSTEM("search-system"),

    /**
     * history-system
     * 
     */
    @XmlEnumValue("history-system")
    HISTORY_SYSTEM("history-system");
    private final java.lang.String value;

    SystemRestfulInteractionList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static SystemRestfulInteractionList fromValue(java.lang.String v) {
        for (SystemRestfulInteractionList c: SystemRestfulInteractionList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
