//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.24 at 10:24:43 PM CET 
//


package org.hl7.fhir.r4.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * If the element is present, it must have either a &#064;value, an &#064;id, or extensions
 * 
 * &lt;p&gt;Java class for VisionPrescription complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="VisionPrescription"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{http://hl7.org/fhir}DomainResource"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="identifier" type="{http://hl7.org/fhir}Identifier" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="status" type="{http://hl7.org/fhir}FinancialResourceStatusCodes"/&amp;gt;
 *         &amp;lt;element name="created" type="{http://hl7.org/fhir}dateTime"/&amp;gt;
 *         &amp;lt;element name="patient" type="{http://hl7.org/fhir}Reference"/&amp;gt;
 *         &amp;lt;element name="encounter" type="{http://hl7.org/fhir}Reference" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="dateWritten" type="{http://hl7.org/fhir}dateTime"/&amp;gt;
 *         &amp;lt;element name="prescriber" type="{http://hl7.org/fhir}Reference"/&amp;gt;
 *         &amp;lt;element name="lensSpecification" type="{http://hl7.org/fhir}VisionPrescription.LensSpecification" maxOccurs="unbounded"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VisionPrescription", propOrder = {
    "identifier",
    "status",
    "created",
    "patient",
    "encounter",
    "dateWritten",
    "prescriber",
    "lensSpecification"
})
public class VisionPrescription
    extends DomainResource
{

    protected List<Identifier> identifier;
    @XmlElement(required = true)
    protected FinancialResourceStatusCodes status;
    @XmlElement(required = true)
    protected DateTime created;
    @XmlElement(required = true)
    protected Reference patient;
    protected Reference encounter;
    @XmlElement(required = true)
    protected DateTime dateWritten;
    @XmlElement(required = true)
    protected Reference prescriber;
    @XmlElement(required = true)
    protected List<VisionPrescriptionLensSpecification> lensSpecification;

    /**
     * Gets the value of the identifier property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the identifier property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getIdentifier().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Identifier }
     * 
     * 
     */
    public List<Identifier> getIdentifier() {
        if (identifier == null) {
            identifier = new ArrayList<Identifier>();
        }
        return this.identifier;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialResourceStatusCodes }
     *     
     */
    public FinancialResourceStatusCodes getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialResourceStatusCodes }
     *     
     */
    public void setStatus(FinancialResourceStatusCodes value) {
        this.status = value;
    }

    /**
     * Gets the value of the created property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getCreated() {
        return created;
    }

    /**
     * Sets the value of the created property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setCreated(DateTime value) {
        this.created = value;
    }

    /**
     * Gets the value of the patient property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getPatient() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setPatient(Reference value) {
        this.patient = value;
    }

    /**
     * Gets the value of the encounter property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getEncounter() {
        return encounter;
    }

    /**
     * Sets the value of the encounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setEncounter(Reference value) {
        this.encounter = value;
    }

    /**
     * Gets the value of the dateWritten property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getDateWritten() {
        return dateWritten;
    }

    /**
     * Sets the value of the dateWritten property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setDateWritten(DateTime value) {
        this.dateWritten = value;
    }

    /**
     * Gets the value of the prescriber property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getPrescriber() {
        return prescriber;
    }

    /**
     * Sets the value of the prescriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setPrescriber(Reference value) {
        this.prescriber = value;
    }

    /**
     * Gets the value of the lensSpecification property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the lensSpecification property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getLensSpecification().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link VisionPrescriptionLensSpecification }
     * 
     * 
     */
    public List<VisionPrescriptionLensSpecification> getLensSpecification() {
        if (lensSpecification == null) {
            lensSpecification = new ArrayList<VisionPrescriptionLensSpecification>();
        }
        return this.lensSpecification;
    }

}
